using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Schick.Plainquire.Sort.Newtonsoft.Extensions;

namespace Schick.Plainquire.Sort.Mvc.Newtonsoft.Extensions;

/// <summary>
/// Extensions to register entity filter extensions to MVC
/// </summary>
public static class MvcBuilderExtensions
{
    /// <summary>
    /// Adds support to serialize/deserialize sort queryable related classes to MVC pipeline.
    /// </summary>
    /// <param name="mvcBuilder">The MVC builder.</param>
    /// <autogeneratedoc />
    public static IMvcBuilder AddSortNewtonsoftSupport(this IMvcBuilder mvcBuilder)
    {
        mvcBuilder.Services.Configure<MvcNewtonsoftJsonOptions>(options =>
        {
            options.SerializerSettings.Converters.AddSortNewtonsoftSupport();
        });

        return mvcBuilder;
    }
}