using Newtonsoft.Json;
using Schick.Plainquire.Sort.Newtonsoft.JsonConverters;
using System.Collections.Generic;

namespace Schick.Plainquire.Sort.Newtonsoft.Extensions;

/// <summary>
/// Extension methods for <see cref="JsonConverter"/>.
/// </summary>
public static class JsonConverterExtensions
{
    /// <summary>
    /// List of Newtonsoft JSON converters required to serialize/deserialize filter expression related classes.
    /// </summary>
    public static readonly JsonConverter[] NewtonsoftConverters =
    [
        new EntitySortConverter(),
        new PropertySortConverter()
    ];

    /// <summary>
    /// Adds support to serialize/deserialize filter expression creator related classes.
    /// </summary>
    /// <param name="converters">The converters.</param>
    /// <autogeneratedoc />
    public static void AddSortQueryableNewtonsoftSupport(this IList<JsonConverter> converters)
    {
        foreach (var converter in NewtonsoftConverters)
            converters.Add(converter);
    }
}