using System.Collections.Generic;
using Schick.Plainquire.Demo.Models;

namespace Schick.Plainquire.Demo.DTOs;

/// <summary>
/// Database query result including execution information.
/// </summary>
public class FreelancerDto
{
    /// <summary>
    /// Data retrieved by database query
    /// </summary>
    public List<Freelancer>? Data { get; init; }

    /// <summary>
    /// Error message, if any
    /// </summary>
    public string? ErrorMessage { get; init; }

    /// <summary>
    /// Count of records return by query
    /// </summary>
    public int FilteredCount { get; init; }

    /// <summary>
    /// Count of records available without filter
    /// </summary>
    /// <autogeneratedoc />
    public int UnfilteredCount { get; init; }

    /// <summary>
    /// Sql command used to query database
    /// </summary>
    public string? SqlQuery { get; set; }

    /// <summary>
    /// Filter expression used to query database
    /// </summary>
    public string? FilterExpression { get; init; }

    /// <summary>
    /// HTTP query used to retrieve data
    /// </summary>
    public string? HttpQuery { get; init; }
}