using Schick.Plainquire.Page.Pages;
using System;

namespace Schick.Plainquire.Page.Extensions;

/// <summary>
/// Extension methods for <see cref="Type"/>.
/// </summary>
internal static class TypeExtensions
{
    /// <summary>
    /// Determines whether the given type is <see cref="EntityPage"/>.
    /// </summary>
    /// <param name="type">The type.</param>
    /// <autogeneratedoc />
    public static bool IsEntityPage(this Type type)
        => typeof(EntityPage).IsAssignableFrom(type);
}