using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Plainquire.Filter.Newtonsoft;

namespace Plainquire.Filter.Mvc.Newtonsoft;

/// <summary>
/// Extensions to register entity filter extensions to MVC
/// </summary>
public static class MvcBuilderExtensions
{
    /// <summary>
    /// Adds support to serialize/deserialize filter expression related classes to MVC pipeline.
    /// </summary>
    /// <param name="mvcBuilder">The MVC builder.</param>
    /// <autogeneratedoc />
    public static IMvcBuilder AddFilterNewtonsoftSupport(this IMvcBuilder mvcBuilder)
    {
        mvcBuilder.Services.Configure<MvcNewtonsoftJsonOptions>(options =>
        {
            options.SerializerSettings.Converters.AddFilterNewtonsoftSupport();
        });

        return mvcBuilder;
    }
}