[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("FS.FilterExpressionCreator.Demo")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("FS.FilterExpressionCreator.Mvc")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("FS.FilterExpressionCreator.Newtonsoft")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("FS.FilterExpressionCreator.Swashbuckle")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("FS.FilterExpressionCreator.Tests")]