using Microsoft.AspNetCore.Mvc.ModelBinding;
using Schick.Plainquire.Page.Pages;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Threading.Tasks;

namespace Schick.Plainquire.Page.Mvc.ModelBinders;

/// <summary>
/// ModelBinder for <see cref="EntityPage{TEntity}"/>
/// Implements <see cref="IModelBinder" />
/// </summary>
/// <seealso cref="IModelBinder" />
[ExcludeFromCodeCoverage]
public class EntityPageSetModelBinder : IModelBinder
{
    private readonly Dictionary<Type, (ModelMetadata, IModelBinder)> _entityFilterBinders;

    /// <summary>
    /// Initializes a new instance of the <see cref="EntityPageSetModelBinder"/> class.
    /// </summary>
    /// <param name="entityFilterBinders">The entity filter binders.</param>
    /// <autogeneratedoc />
    public EntityPageSetModelBinder(Dictionary<Type, (ModelMetadata, IModelBinder)> entityFilterBinders)
        => this._entityFilterBinders = entityFilterBinders;

    /// <inheritdoc />
    public async Task BindModelAsync(ModelBindingContext bindingContext)
    {
        if (bindingContext == null)
            throw new ArgumentNullException(nameof(bindingContext));

        var entityPageSet = Activator.CreateInstance(bindingContext.ModelType);
        if (entityPageSet == null)
            throw new InvalidOperationException($"Cannot create instance of filter set '{bindingContext.ModelType.Name}'");

        var entityFilterProperties = entityPageSet.GetType().GetProperties();
        foreach (var entityFilter in entityFilterProperties)
        {
            var (modelMetadata, modelBinder) = _entityFilterBinders[entityFilter.PropertyType];
            var newBindingContext = DefaultModelBindingContext.CreateBindingContext(
                bindingContext.ActionContext,
                bindingContext.ValueProvider,
                modelMetadata,
                bindingInfo: null,
                bindingContext.ModelName);
            await modelBinder.BindModelAsync(newBindingContext);
            entityFilter.SetValue(entityPageSet, newBindingContext.Result.Model);
        }

        bindingContext.Result = ModelBindingResult.Success(entityPageSet);
    }
}