using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Threading.Tasks;

namespace Plainquire.Page.Mvc.ModelBinders;

/// <summary>
/// ModelBinder for <see cref="EntityPage{TEntity}"/>
/// Implements <see cref="IModelBinder" />
/// </summary>
/// <seealso cref="IModelBinder" />
[ExcludeFromCodeCoverage]
public class EntityPageSetModelBinder : IModelBinder
{
    private readonly IDictionary<Type, (ModelMetadata, IModelBinder)> _entityPageBinders;

    /// <summary>
    /// Initializes a new instance of the <see cref="EntityPageSetModelBinder"/> class.
    /// </summary>
    /// <param name="entityPageBinders">The entity page binders.</param>
    /// <autogeneratedoc />
    public EntityPageSetModelBinder(IDictionary<Type, (ModelMetadata, IModelBinder)> entityPageBinders)
        => this._entityPageBinders = entityPageBinders;

    /// <inheritdoc />
    public async Task BindModelAsync(ModelBindingContext bindingContext)
    {
        if (bindingContext == null)
            throw new ArgumentNullException(nameof(bindingContext));

        var entityPageSet = Activator.CreateInstance(bindingContext.ModelType)
            ?? throw new InvalidOperationException($"Cannot create instance of page set '{bindingContext.ModelType.Name}'");

        var entityPageProperties = entityPageSet.GetType().GetProperties();

        foreach (var entityPage in entityPageProperties)
        {
            var (modelMetadata, modelBinder) = _entityPageBinders[entityPage.PropertyType];

            var pageBindingContext = DefaultModelBindingContext.CreateBindingContext(
                bindingContext.ActionContext,
                bindingContext.ValueProvider,
                modelMetadata,
                bindingInfo: null,
                bindingContext.OriginalModelName);

            await modelBinder.BindModelAsync(pageBindingContext);

            entityPage.SetValue(entityPageSet, pageBindingContext.Result.Model);
        }

        bindingContext.Result = ModelBindingResult.Success(entityPageSet);
    }
}