using Schick.Plainquire.Sort.Sorts;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Threading.Tasks;

namespace Schick.Plainquire.Sort.Mvc.ModelBinders;

/// <summary>
/// ModelBinder for <see cref="EntitySort{TEntity}"/>
/// Implements <see cref="IModelBinder" />
/// </summary>
/// <seealso cref="IModelBinder" />
[ExcludeFromCodeCoverage]
public class EntitySortSetModelBinder : IModelBinder
{
    private readonly Dictionary<Type, (ModelMetadata, IModelBinder)> _entityFilterBinders;

    /// <summary>
    /// Initializes a new instance of the <see cref="EntitySortSetModelBinder"/> class.
    /// </summary>
    /// <param name="entityFilterBinders">The entity filter binders.</param>
    /// <autogeneratedoc />
    public EntitySortSetModelBinder(Dictionary<Type, (ModelMetadata, IModelBinder)> entityFilterBinders)
        => this._entityFilterBinders = entityFilterBinders;

    /// <inheritdoc />
    public async Task BindModelAsync(ModelBindingContext bindingContext)
    {
        if (bindingContext == null)
            throw new ArgumentNullException(nameof(bindingContext));

        var entitySortSet = Activator.CreateInstance(bindingContext.ModelType);
        if (entitySortSet == null)
            throw new InvalidOperationException($"Cannot create instance of filter set '{bindingContext.ModelType.Name}'");

        var entityFilterProperties = entitySortSet.GetType().GetProperties();
        foreach (var entityFilter in entityFilterProperties)
        {
            var (modelMetadata, modelBinder) = _entityFilterBinders[entityFilter.PropertyType];
            var newBindingContext = DefaultModelBindingContext.CreateBindingContext(
                bindingContext.ActionContext,
                bindingContext.ValueProvider,
                modelMetadata,
                bindingInfo: null,
                bindingContext.ModelName);
            await modelBinder.BindModelAsync(newBindingContext);
            entityFilter.SetValue(entitySortSet, newBindingContext.Result.Model);
        }

        bindingContext.Result = ModelBindingResult.Success(entitySortSet);
    }
}