using FS.FilterExpressionCreator.Newtonsoft.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;

namespace FS.FilterExpressionCreator.Mvc.Newtonsoft.Extensions
{
    /// <summary>
    /// Extensions to register entity filter extensions to MVC
    /// </summary>
    public static class MvcBuilderExtensions
    {
        /// <summary>
        /// Adds support to serialize/deserialize filter expression creator related classes to MVC pipeline.
        /// </summary>
        /// <param name="mvcBuilder">The MVC builder.</param>
        /// <autogeneratedoc />
        public static IMvcBuilder AddFilterExpressionsNewtonsoftSupport(this IMvcBuilder mvcBuilder)
        {
            mvcBuilder.Services.Configure<MvcNewtonsoftJsonOptions>(options =>
            {
                options.SerializerSettings.Converters.AddFilterExpressionsNewtonsoftSupport();
            });

            return mvcBuilder;
        }
    }
}
