[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Plainquire.Filter")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Plainquire.Filter.Tests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Plainquire.Page.Mvc")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Plainquire.Page.Swashbuckle")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Plainquire.Sort")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Plainquire.Sort.Mvc")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Plainquire.Sort.Swashbuckle")]