using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Schick.Plainquire.Sort.Mvc.ModelBinders;

namespace Schick.Plainquire.Sort.Mvc.Extensions;

/// <summary>
/// Extensions to register entity filter extensions to MVC
/// </summary>
public static class MvcBuilderExtensions
{
    /// <summary>
    /// Registers filter expression creators specific model binders.
    /// </summary>
    /// <param name="mvcBuilder">The MVC builder.</param>
    /// <autogeneratedoc />
    public static IMvcBuilder AddSortQueryableSupport(this IMvcBuilder mvcBuilder)
    {
        mvcBuilder.Services.Configure<MvcOptions>(options =>
        {
            options.ModelBinderProviders.Insert(0, new EntitySortModelBinderProvider());
            options.ModelBinderProviders.Insert(0, new EntitySortSetModelBinderProvider());
        });

        return mvcBuilder;
    }
}