using System.Collections.Generic;
using Newtonsoft.Json;
using Plainquire.Page.Newtonsoft.JsonConverters;

namespace Plainquire.Page.Newtonsoft.Extensions;

/// <summary>
/// Extension methods for <see cref="JsonConverter"/>.
/// </summary>
public static class JsonConverterExtensions
{
    /// <summary>
    /// List of Newtonsoft JSON converters required to serialize/deserialize page related classes.
    /// </summary>
    public static readonly JsonConverter[] NewtonsoftConverters = [
        new EntityPageConverter()
    ];

    /// <summary>
    /// Adds support to serialize/deserialize page related classes.
    /// </summary>
    /// <param name="converters">The converters.</param>
    /// <autogeneratedoc />
    public static void AddPageNewtonsoftSupport(this IList<JsonConverter> converters)
    {
        foreach (var converter in NewtonsoftConverters)
            converters.Add(converter);
    }
}